---
- label: Patient (R5)
  dataFormat: Turtle
  dataURL: playground/manifests/patient-example.ttl
  resourceType: 'Patient'
  sparqlQueries:
    - label: family and given names
      sparqlQuery: |
        PREFIX fhir: <http://hl7.org/fhir/>
        PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
        PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
       
        SELECT ?id ?active ?family ?given {
          ?resource a fhir:Patient ;
            fhir:id [ fhir:v ?id ] ;
            fhir:active [ fhir:v ?active ] ;
            fhir:name [ rdf:rest*/rdf:first [
              fhir:use [ fhir:v "official" ] ;
              fhir:family [ fhir:v ?family ] ;
              fhir:given [ rdf:rest*/rdf:first [ fhir:v ?given ] ]
            ] ]
        }
    - label: text
      sparqlQuery: |
        PREFIX fhir: <http://hl7.org/fhir/>

        SELECT ?id ?div {
          ?resource fhir:nodeRole fhir:treeRoot ;
            fhir:id [ fhir:v ?id ] ;
            fhir:text [
              fhir:div ?div
            ] .
        }

- label: foo
- label: bar
- label: baz
