---
- manifestLabel: Patient (R5)
  dataFormat: Turtle
  dataURL: playground/manifests/patient-example.ttl
  resourceType: 'Patient'
  sparqlQuery: |
    PREFIX fhir: <http://hl7.org/fhir/>
    PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
    
    SELECT ?id ?active ?family ?given {
      ?resource a fhir:Patient ;
        fhir:id [ fhir:v ?id ] ;
        fhir:active [ fhir:v ?active ] ;
        fhir:name [ rdf:rest*/rdf:first [
          fhir:use [ fhir:v "official" ] ;
          fhir:family [ fhir:v ?family ] ;
          fhir:given [ rdf:rest*/rdf:first [ fhir:v ?given ] ]
        ] ]
    }
  text: "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p style=\"border: 1px #661aff solid; background-color: #e6e6ff; padding: 10px;\"><b>Jim </b> male, DoB: 1974-12-25 ( Medical record number: 12345 (use: USUAL, period: 2001-05-06 --&gt; (ongoing)))</p><hr/><table class=\"grid\"><tr><td style=\"background-color: #f3f5da\" title=\"Record is active\">Active:</td><td>true</td><td style=\"background-color: #f3f5da\" title=\"Known status of Patient\">Deceased:</td><td colspan=\"3\">false</td></tr><tr><td style=\"background-color: #f3f5da\" title=\"Alternate names (see the one above)\">Alt Names:</td><td colspan=\"3\"><ul><li>Peter James Chalmers (OFFICIAL)</li><li>Peter James Windsor (MAIDEN)</li></ul></td></tr><tr><td style=\"background-color: #f3f5da\" title=\"Ways to contact the Patient\">Contact Details:</td><td colspan=\"3\"><ul><li>-unknown-(HOME)</li><li>ph: (03) 5555 6473(WORK)</li><li>ph: (03) 3410 5613(MOBILE)</li><li>ph: (03) 5555 8834(OLD)</li><li>534 Erewhon St PeasantVille, Rainbow, Vic  3999(HOME)</li></ul></td></tr><tr><td style=\"background-color: #f3f5da\" title=\"Nominated Contact: Next-of-Kin\">Next-of-Kin:</td><td colspan=\"3\"><ul><li>Bénédicte du Marché  (female)</li><li>534 Erewhon St PleasantVille Vic 3999 (HOME)</li><li><a href=\"tel:+33(237)998327\">+33 (237) 998327</a></li><li>Valid Period: 2012 --&gt; (ongoing)</li></ul></td></tr><tr><td style=\"background-color: #f3f5da\" title=\"Patient Links\">Links:</td><td colspan=\"3\"><ul><li>Managing Organization: <a href=\"organization-example-gastro.html\">Organization/1</a> &quot;Gastroenterology&quot;</li></ul></td></tr></table></div>"

- manifestLabel: Structured Values and Shorthand Properties
  schema: |
    PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    PREFIX bf: <http://id.loc.gov/ontologies/bibframe/>
    PREFIX Map: <http://shex.io/extensions/Map/#>
    PREFIX x: <http://idunno.example/bindings#>
    
    </identifiedByShape> {
      bf:identifiedBy {
        a [bf:Isbn] ;
        rdf:value LITERAL %Map:{ x:isbn %}
      }
    }
  dataFormat: Turtle
  data: |
    PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    PREFIX bf: <http://id.loc.gov/ontologies/bibframe/>
    
    </instance/a>
        bf:identifiedBy [ a bf:Isbn ; rdf:value "12-3456-789-0" ] .
  queryMap: "<instance/a>@<identifiedByShape>"
  outputSchema: |
    prefix schema: <http://schema.org/>
    PREFIX Map: <http://shex.io/extensions/Map/#>
    PREFIX x: <http://idunno.example/bindings#>
    
    </isbnShape> {
      schema:isbn LITERAL %Map:{ x:isbn %}
    }
  outputShape: "</isbnShape>"
  staticVars:
    http://abc.example/someConstant: '"123-456"'
  createRoot: "<http://idunno.example>"
  status: conformant

- manifestLabel: Qualified Relations as Reifications
  dataFormat: Turtle
  dataURL: foo.ttl
  queryMap: "<work>@<workShape>"
  outputSchema: |
    PREFIX dc: <http://purl.org/dc/terms/>
    PREFIX Map: <http://shex.io/extensions/Map/#>
    PREFIX x: <http://idunno.example/bindings#>
    
    </workShape2> {
      dc:contributor IRI %Map:{ x:contrib %}
    }
  outputShape: "</workShape2>"
  staticVars:
    http://abc.example/someConstant: '"123-456"'
  createRoot: "<http://idunno.example>"
  status: conformant

- manifestLabel: Reification and Events
  schema: |
    PREFIX bf: <http://id.loc.gov/ontologies/bibframe/>
    PREFIX Map: <http://shex.io/extensions/Map/#>
    PREFIX x: <http://idunno.example/bindings#>
    
    <BfShape> {
      bf:provisionActivity {
        a [bf:Publication] ;
        bf:agent IRI %Map:{ x:contrib %} ;
        bf:date LITERAL %Map:{ x:when %}
      }
    }
  dataLabel: 
  data: |
    PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    PREFIX bf: <http://id.loc.gov/ontologies/bibframe/>
    
    </instance/a>
      bf:provisionActivity [
        a bf:Publication ;
        bf:agent </org/a> ;
        bf:date "2017"
      ] .
  queryMap: "<instance/a>@<BfShape>"
  outputSchema: |
    PREFIX schema: <http://schema.org/>
    PREFIX Map: <http://shex.io/extensions/Map/#>
    PREFIX x: <http://idunno.example/bindings#>
    
    </SchemaShape> {
      schema:publisher IRI %Map:{ x:contrib %};
      schema:datePublished LITERAL %Map:{ x:when %}
    }
  outputShape: "</SchemaShape>"
  staticVars:
    http://abc.example/someConstant: '"123-456"'
  createRoot: "<http://idunno.example>"
  status: conformant
