---
- label: Patient (R5)
  dataFormat: Turtle
  dataURL: patient-example.ttl
  resourceType: 'Patient'
  sparqlQueries:
    - label: family and given names
      action: query
      sparqlQuery: |
        PREFIX fhir: <http://hl7.org/fhir/>
        PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
        PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
       
        SELECT ?id ?active ?family ?given {
          ?resource a fhir:Patient ;
            fhir:id [ fhir:v ?id ] ;
            fhir:active [ fhir:v ?active ] ;
            fhir:name [ rdf:rest*/rdf:first [
              fhir:use [ fhir:v "official" ] ;
              fhir:family [ fhir:v ?family ] ;
              fhir:given [ rdf:rest*/rdf:first [ fhir:v ?given ] ]
            ] ]
        }

    - label: narrative
      action: query
      sparqlQuery: |
        PREFIX fhir: <http://hl7.org/fhir/>

        SELECT ?id ?div {
          ?resource fhir:nodeRole fhir:treeRoot ;
            fhir:id [ fhir:v ?id ] ;
            fhir:text [
              fhir:div ?div
            ] .
        }

    - label: validate as Patient
      action: validate
      shexSchemaURL: //fhircat.github.io/ShExValidation/fhir_rdf_validation/ShExSchemas/R5/Patient.shex

    - label: validate as Observation
      action: validate
      shexSchemaURL: //fhircat.github.io/ShExValidation/fhir_rdf_validation/ShExSchemas/R5/Observation.shex

- label: Patient (R5) JSON
  dataFormat: JSON
  dataURL: patient-example.json
  resourceType: 'Patient'
  sparqlQueries:
    - label: family and given names
      action: query
      sparqlQuery: |
        PREFIX fhir: <http://hl7.org/fhir/>
        PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
        PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
       
        SELECT ?id ?active ?family ?given {
          ?resource a fhir:Patient ;
            fhir:id [ fhir:v ?id ] ;
            fhir:active [ fhir:v ?active ] ;
            fhir:name [ rdf:rest*/rdf:first [
              fhir:use [ fhir:v "official" ] ;
              fhir:family [ fhir:v ?family ] ;
              fhir:given [ rdf:rest*/rdf:first [ fhir:v ?given ] ]
            ] ]
        }

    - label: narrative
      action: query
      sparqlQuery: |
        PREFIX fhir: <http://hl7.org/fhir/>

        SELECT ?id ?div {
          ?resource fhir:nodeRole fhir:treeRoot ;
            fhir:id [ fhir:v ?id ] ;
            fhir:text [
              fhir:div ?div
            ] .
        }

    - label: validate as Patient
      action: validate
      shexSchemaURL: //fhircat.github.io/ShExValidation/fhir_rdf_validation/ShExSchemas/R5/Patient.shex

    - label: validate as Observation
      action: validate
      shexSchemaURL: //fhircat.github.io/ShExValidation/fhir_rdf_validation/ShExSchemas/R5/Observation.shex

- label: a smoker
  dataFormat: Turtle
  dataURL:
    - Observation/smoker-1_smoking-2023-06-20.ttl
    - Patient/smoker-1.ttl
    - Observation/smoker-1_smoking-2022-05-19.ttl
    - Observation/smoker-1_A1c.ttl
    - DiagnosticReport/smoker-1_history_1924-11-23.ttl
  resourceType: Observation
  sparqlQueries:
    - label: smoker-min
      action: query
      sparqlQueryURL: smoker-min.rq

    - label: smoker-coding
      action: query
      sparqlQueryURL: smoker-codings.rq

- label: smokerz
  dataFormat: -none-
  sparqlQueries:
    - label: smoking-status
      action: fhir
      sparqlQueryURL: obs-pat_tobacco-smoking-status.rq

    - label: full query
      action: fhir
      sparqlQueryURL: smoker-min.rq

- label: a smoker cohort
  dataFormat: -none-
  action: fhir
  sparqlQueryURL: smoker-min.rq
